//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADProjGp2_LogicUStationeryStore
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
            this.SpecialRequests = new HashSet<SpecialRequest>();
        }
    
        public string requisitionId { get; set; }
        public string employee { get; set; }
        public string approvalPerson { get; set; }
        public string status { get; set; }
        public System.DateTime requestDate { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string retrievalId { get; set; }
        public string disbursementId { get; set; }
        public string remark { get; set; }
        public string departmentId { get; set; }
    
        [JsonIgnore]
        public virtual Disbursement Disbursement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<SpecialRequest> SpecialRequests { get; set; }
        [JsonIgnore]
        public virtual Retrieval Retrieval { get; set; }
    }
}
