//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADProjGp2_LogicUStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        public int transId { get; set; }
        public string requisitionId { get; set; }
        public string itemId { get; set; }
        public int requestQty { get; set; }
        public Nullable<int> retrieveQty { get; set; }
        public Nullable<int> adjustQty { get; set; }
        public string remark { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
